- name: Install PostgreSQL
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    state: present
  become: yes

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: Create database
  community.postgresql.postgresql_db:
    name: flask_db
    login_user: postgres
    login_password: ""
    login_host: localhost
    login_unix_socket: /var/run/postgresql
  become: true
  tags:
    - create_db

- name: Create database user
  postgresql_user:
    login_user: postgres
    login_password: ""
    login_host: localhost
    login_unix_socket: /var/run/postgresql
    db: flask_db
    name: flask_user
    password: "{{ db_password }}"
    priv: ALL
    state: present
  become: yes
  tags:
    - create_user

- name: Allow remote connections
  lineinfile:
    path: /etc/postgresql/15/main/postgresql.conf
    regexp: '^#listen_addresses'
    line: "listen_addresses = '*'"
  notify: Restart PostgreSQL

- name: Add multiple lines to pg_hba.conf for remote access
  blockinfile:
    path: /etc/postgresql/15/main/pg_hba.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR REMOTE ACCESS"
    block: |
      host    all             all             192.168.56.0/24       md5
      host    all             all             192.168.1.0/24       md5
  notify: Restart PostgreSQL