all:
  vars:
    ansible_user: vagrant
  children:
    web:
      hosts:
        web1:
          ansible_host: 192.168.1.51
          ansible_ssh_private_key_file: ~/ssh_private_key/web1/private_key
          ansible_python_interpreter: /usr/bin/python3.11
        web2:
          ansible_host: 192.168.1.52
          ansible_ssh_private_key_file: ~/ssh_private_key/web2/private_key
          ansible_python_interpreter: /usr/bin/python3.11
    db:
      hosts:
        web1:
          ansible_host: 192.168.1.51
          ansible_ssh_private_key_file: ~/ssh_private_key/web1/private_key
          ansible_python_interpreter: /usr/bin/python3.11
    lb:
      hosts:
        lb1:
          ansible_host: 192.168.1.53
          ansible_ssh_private_key_file: ~/ssh_private_key/lb/private_key
          ansible_python_interpreter: /usr/bin/python3.11
    monitoring:
      hosts:
        lb1:
          ansible_host: 192.168.1.53
          ansible_ssh_private_key_file: ~/ssh_private_key/lb/private_key
          ansible_python_interpreter: /usr/bin/python3.11