- name: Setup infrastructure
  hosts: all
  become: yes
  roles:
    - common

- name: Setup web servers
  hosts: web
  become: yes
  roles:
    - nginx
    - app

- name: Setup database
  hosts: db
  become: yes
  roles:
    - database

- name: Setup load balancer and monitoring
  hosts: lb
  become: yes
  roles:
    - haproxy
    - monitoring
